[package]
name = "unimarkup-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.26"
features = ["bundled"]

[dependencies]
unicode-segmentation = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_rusqlite = "0.28.0"
serde_bytes = "0.11.5"
serde_json = "1.0"
serde_plain = "1.0.0"
strum = "0.22.0"
strum_macros = "0.22.0"
log = "0.4"
simple_logger = "1.13"
pest = "2.1.3"
pest_derive = "2.0"
