[workspace]
members = [
    "render",
    "cli",
    "core",
    "inline",
    "system_tests"
]

[workspace.package]
version = "0.3.0"
edition = "2021"
authors = ["Manuel Hatzl", "Nadir Fejzić"]
description = "Unimarkup compiler written in Rust."
repository = "https://github.com/Unimarkup/unimarkup-rs"
readme = "README.md"
license = "MIT"

[workspace.dependencies]
logid = { version = "0.6.0", features = ["diagnostics", "causes"] }
once_cell = "1.13.0"
clap = { version = "^3.1.0", features = ["derive", "cargo", "env"] }
