[package]
name = "unimarkup_inline"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.26"
features = ["bundled"]

[dependencies]
log = "0.4"
