[package]
name = "unimarkup-inline"
description = "Compiler for Unimarkup inline elements."
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logid.workspace = true
unimarkup-render = { path = "../render/" }
unicode-segmentation = "1.8.0"
