on:
  push:
    branches:
      - main

name: Release Please

jobs:
  release-build:
    name: Build unimarkup release
    uses: ./.github/workflows/build-workflow.yml
    with:
      release: true
      upload-artifacts: true

  release-please:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
      - name: Download Artifacts
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/download-artifact@v4
      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
        run: |
          ls -la
          mv -v unimarkup-ubuntu-latest/unimarkup ./unimarkup-linux
          mv -v unimarkup-windows-latest/unimarkup.exe ./unimarkup-win.exe
          mv -v unimarkup-macos-latest/unimarkup ./unimarkup-macos
          ls -la
          gh release upload ${{ steps.release.outputs.tag_name }} ./unimarkup-linux ./unimarkup-win.exe ./unimarkup-macos
