on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.unimarkup-rs--release_created }}
      tag-name: ${{ steps.release.outputs.unimarkup-rs--tag_name }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release

  release-build:
    name: Build unimarkup release
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    uses: ./.github/workflows/build-workflow.yml
    with:
      release: true
      upload-artifacts: true

  upload-executables:
    runs-on: ubuntu-latest
    needs:
      - release-please
      - release-build
    if: ${{ needs.release-please.outputs.release-created }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Upload Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
        run: |
          ls -la
          mv -v unimarkup-ubuntu-latest/unimarkup ./unimarkup-linux
          mv -v unimarkup-windows-latest/unimarkup.exe ./unimarkup-win.exe
          mv -v unimarkup-macos-latest/unimarkup ./unimarkup-macos
          ls -la
          gh release upload ${{ needs.release-please.outputs.tag-name }} ./unimarkup-linux ./unimarkup-win.exe ./unimarkup-macos
