on:
  push:
    branches:
      - main

name: Release Please

jobs:
  release-build:
    name: Build unimarkup release
    uses: ./.github/workflows/build-workflow.yml
    with:
      release: true
      upload-artifacts: true

  release-please:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: rust
          package-name: unimarkup-rs
          # Breaking changes might happen frequently before 1.0.0 => only bump minor
          bump-minor-pre-major: true
          changelog-types: >
            [
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"arch","section":"Architecture/Refactor","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":true}
            ]
      - name: Download Artifacts
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/download-artifact@v4
      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv unimarkup-ubuntu-latest/unimarkup ./unimarkup-linux
          mv unimarkup-windows-latest/unimarkup.exe ./unimarkup-win.exe
          mv unimarkup-macos-latest/unimarkup ./unimarkup-macos
          gh release upload ${{ steps.release.outputs.tag_name }} unimarkup-linux unimarkup-win.exe unimarkup-macos
