name: Tests & Lints

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main, feature ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build unimarkup
    uses: ./.github/workflows/build-workflow.yml
    with:
      os: "[ubuntu-latest${{ github.ref == 'refs/heads/main'  ', windows-latest, macos-latest' || ''}}]"
      enable-caching: true

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: cargo fmt -- --check

  lint:
    name: Run Linter (clippy)
    runs-on: ubuntu-latest
    needs: [ format, build ]
    
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-files"
      - name: Run linter
        run: cargo clippy -- -D warnings
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-files"
      - name: Run tests
        run: cargo test --verbose
