name: UniMarkup Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Workflow
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      
  lint:
    name: Lint Workflow
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: cargo clippy -- -D warnings

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt -- --check
